FROM crystallang/crystal:0.35.1-alpine

# Based on https://github.com/emcrisostomo/fswatch/blob/master/docker/alpine/Dockerfile.in

RUN apk add --no-cache file git autoconf automake libtool gettext gettext-dev make g++ texinfo curl

ENV ROOT_HOME /root
ENV FSWATCH_BRANCH 1.14.0

WORKDIR ${ROOT_HOME}
RUN git clone https://github.com/emcrisostomo/fswatch.git

WORKDIR ${ROOT_HOME}/fswatch
RUN git checkout ${FSWATCH_BRANCH}
RUN ./autogen.sh && ./configure && make -j
RUN make install
