<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mare</string>
	</array>
	<key>name</key>
	<string>Mare</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\s*//)</string>
			<key>comment</key>
			<string>Line Comment</string>
			<key>end</key>
			<string>($)</string>
			<key>name</key>
			<string>comment.line.mare</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>comment</key>
			<string>Double-Quote String</string>
			<key>end</key>
			<string>(")</string>
			<key>name</key>
			<string>string.quoted.double.mare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.mare</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.mare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class (or other type)</string>
			<key>match</key>
			<string>(?:::)?([A-Z][_a-zA-Z0-9]*)</string>
			<key>name</key>
			<string>meta.class.mare</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(:)(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declare.mare</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.declare.mare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Declare</string>
			<key>end</key>
			<string>(:)|\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declare.mare</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declare.mare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\w+)</string>
					<key>name</key>
					<string>entity.other.attribute-name.mare</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error-Raising Calls/Names</string>
			<key>match</key>
			<string>(\w+\!)</string>
			<key>name</key>
			<string>markup.deleted.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric Values</string>
			<key>match</key>
			<string>\b\d([\d_]*(\.[\d_]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hex Numeric Values</string>
			<key>match</key>
			<string>\b0x([\h_]+)\b</string>
			<key>name</key>
			<string>constant.numeric.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Binary Numeric Values</string>
			<key>match</key>
			<string>\b0b([01_]+)\b</string>
			<key>name</key>
			<string>constant.numeric.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function Call (with braces)</string>
			<key>match</key>
			<string>(\w+(?:\?|\!)?)(?=\()</string>
			<key>name</key>
			<string>entity.name.function.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function Call (with receiver)</string>
			<key>match</key>
			<string>(?&lt;=\.)(\w+(?:\?|\!)?)</string>
			<key>name</key>
			<string>support.function.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function Call (with self receiver)</string>
			<key>match</key>
			<string>(?&lt;=@)(\w+(?:\?|\!)?)</string>
			<key>name</key>
			<string>support.function.mare</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.paren.mare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parenthesis</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.paren.mare</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.parens.mare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.brace.mare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Brace</string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.brace.mare</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.braces.mare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.bracket.mare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Bracket</string>
			<key>end</key>
			<string>(\])(\!)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.bracket.mare</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.deleted.mare</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.brackets.mare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.bracket.mare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Bracket</string>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.bracket.mare</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.brackets.mare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Expression Separators</string>
			<key>match</key>
			<string>(\,|\;|\:)</string>
			<key>name</key>
			<string>punctuation.separator.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other "Punctuation"</string>
			<key>match</key>
			<string>(@)</string>
			<key>name</key>
			<string>punctuation.receiver.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Piping Operators</string>
			<key>match</key>
			<string>(\|\&gt;)</string>
			<key>name</key>
			<string>keyword.operator.pipe.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Branching Operators</string>
			<key>match</key>
			<string>(\&amp;\&amp;|\|\||\?\?|\&amp;\?|\|\?|\.\?)</string>
			<key>name</key>
			<string>keyword.operator.compound.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comparison Operators</string>
			<key>match</key>
			<string>(\&lt;\=\&gt;|\=\~|\=\=|\&lt;\=|\&gt;\=|\&lt;|\&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Arithmetic Operators</string>
			<key>match</key>
			<string>(\+|\-|\/|\*|\%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assignment Operators</string>
			<key>match</key>
			<string>(\=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.mare</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other Operators</string>
			<key>match</key>
			<string>(\!|\&lt;\&lt;|\&lt;|\&amp;|\|)</string>
			<key>name</key>
			<string>keyword.operator.other.mare</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mare</string>
	<key>uuid</key>
	<string>6d792077-696c-6465-7374-20647265616d</string>
</dict>
</plist>
