<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Savi</string>
    <key>scopeName</key>
    <string>source.savi</string>
    <key>fileTypes</key>
    <array>
      <string>savi</string>
    </array>
    <key>uuid</key>
    <string>6d792077-696c-6465-7374-20647265616d</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>Line Comment</string>
        <key>name</key>
        <string>comment.line.savi</string>
        <key>begin</key>
        <string>\s*(//)</string>
        <key>end</key>
        <string>($)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Doc Comment</string>
        <key>name</key>
        <string>comment.doc.savi</string>
        <key>begin</key>
        <string>\s*(::)</string>
        <key>end</key>
        <string>($)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Capability Operator</string>
        <key>name</key>
        <string>meta.operator.capability.savi</string>
        <key>match</key>
        <string>(\')(\w+)(?=[^\'])</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.capability.savi</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.identifier.savi</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Double-Quote String</string>
        <key>name</key>
        <string>string.quoted.double.savi</string>
        <key>begin</key>
        <string>(\w?")</string>
        <key>end</key>
        <string>(")</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#interpolation</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.character.escape.savi</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Single-Char String</string>
        <key>name</key>
        <string>string.quoted.single.savi</string>
        <key>begin</key>
        <string>(')</string>
        <key>end</key>
        <string>(')</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.savi</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Class (or other type)</string>
        <key>name</key>
        <string>meta.class.savi</string>
        <key>match</key>
        <string>(_?[A-Z]\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.savi</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Declare</string>
        <key>name</key>
        <string>meta.declare.savi</string>
        <key>begin</key>
        <string>^\s*(:)(\w+)</string>
        <key>end</key>
        <string>(:)|\n</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declare.savi</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.declare.savi</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.declare.savi</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.other.attribute-name.savi</string>
            <key>match</key>
            <string>\b[a-z_]\w*\b(?!\!)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Error-Raising Calls/Names</string>
        <key>name</key>
        <string>markup.deleted.savi</string>
        <key>match</key>
        <string>((\w+|\+|\-|\*)\!)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Numeric Values</string>
        <key>name</key>
        <string>constant.numeric.savi</string>
        <key>match</key>
        <string>\b\d([\d_]*(\.[\d_]+)?)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Hex Numeric Values</string>
        <key>name</key>
        <string>constant.numeric.savi</string>
        <key>match</key>
        <string>\b0x([0-9a-fA-F_]+)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Binary Numeric Values</string>
        <key>name</key>
        <string>constant.numeric.savi</string>
        <key>match</key>
        <string>\b0b([01_]+)\b</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Function Call (with braces)</string>
        <key>name</key>
        <string>entity.name.function.savi</string>
        <key>match</key>
        <string>(\w+(?:\?|\!)?)(?=\()</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Function Call (with receiver)</string>
        <key>name</key>
        <string>support.function.savi</string>
        <key>match</key>
        <string>(?&lt;=\.)(\w+(?:\?|\!)?)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Function Call (with self receiver)</string>
        <key>name</key>
        <string>support.function.savi</string>
        <key>match</key>
        <string>(?&lt;=@)(\w+(?:\?|\!)?)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Parenthesis</string>
        <key>name</key>
        <string>meta.parens.savi</string>
        <key>begin</key>
        <string>(\()</string>
        <key>end</key>
        <string>(\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.paren.savi</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.paren.savi</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Brace</string>
        <key>name</key>
        <string>meta.braces.savi</string>
        <key>begin</key>
        <string>(\{)</string>
        <key>end</key>
        <string>(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.brace.savi</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.brace.savi</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Bracket</string>
        <key>name</key>
        <string>meta.brackets.savi</string>
        <key>begin</key>
        <string>(\[)</string>
        <key>end</key>
        <string>(\])(\!)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.bracket.savi</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.bracket.savi</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>markup.deleted.savi</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Bracket</string>
        <key>name</key>
        <string>meta.brackets.savi</string>
        <key>begin</key>
        <string>(\[)</string>
        <key>end</key>
        <string>(\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.bracket.savi</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.bracket.savi</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Expression Separators</string>
        <key>name</key>
        <string>punctuation.separator.savi</string>
        <key>match</key>
        <string>(\,|\;|\:)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Other "Punctuation"</string>
        <key>name</key>
        <string>punctuation.receiver.savi</string>
        <key>match</key>
        <string>(@|\.)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Piping Operators</string>
        <key>name</key>
        <string>keyword.operator.pipe.savi</string>
        <key>match</key>
        <string>(\|\&gt;)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Branching Operators</string>
        <key>name</key>
        <string>keyword.operator.compound.savi</string>
        <key>match</key>
        <string>(\&amp;\&amp;|\|\||\?\?|\&amp;\?|\|\?|\.\?)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Comparison Operators</string>
        <key>name</key>
        <string>keyword.operator.comparison.savi</string>
        <key>match</key>
        <string>(\&lt;\=\&gt;|\=\~|\=\=|\&lt;\=|\&gt;\=|\&lt;|\&gt;)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Arithmetic Operators</string>
        <key>name</key>
        <string>keyword.operator.arithmetic.savi</string>
        <key>match</key>
        <string>(\+|\-|\/|\*|\%)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Assignment Operators</string>
        <key>name</key>
        <string>keyword.operator.assignment.savi</string>
        <key>match</key>
        <string>(\=)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Other Operators</string>
        <key>name</key>
        <string>keyword.operator.other.savi</string>
        <key>match</key>
        <string>(\!|\&lt;\&lt;|\&lt;|\&amp;|\|)</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Identifiers</string>
        <key>name</key>
        <string>entity.name.identifier.savi</string>
        <key>match</key>
        <string>\w+</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>interpolation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>String Interpolation</string>
            <key>name</key>
            <string>meta.embedded.savi</string>
            <key>begin</key>
            <string>(\\\()</string>
            <key>end</key>
            <string>(\))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.savi</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.savi</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>