require "./capnproto/segment"
require "./capnproto/pointer_far"
require "./capnproto/pointer_u8_list"
require "./capnproto/pointer_struct"
require "./capnproto/pointer_struct_list"
require "./capnproto/list"
require "./capnproto/meta"
